### ISSUE TITLE
session log bucket target is toggling

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/iac#104]
On each tf plan/apply after the initial deployment, the `session_logs_bucket.target_bucket` field appears to toggle between `session_logs` and `access-logs`. Additionally, it looks like the suffix is updated resulting in a change warning that looks like this:
```
  # module.bastion.aws_s3_bucket_logging.session_logs_bucket will be updated in-place
  ~ resource "aws_s3_bucket_logging" "session_logs_bucket" {
        id            = "ve-bastion-dev-session-logs-20230214070204348100000004"
      ~ target_bucket = "ve-bastion-dev-access-logs-20230214070204348100000003" -> "ve-bastion-dev-session-logs-20230214070204348100000004"
        # (2 unchanged attributes hidden)
    }
    ```

**Comment by RothAndrew** [comment]
I'll take a look. It's possible I screwed something up with that automated testing PR

**Comment by RothAndrew** [comment]
Hmnm. The code for that resource hasn't changed in 2 months.

```
resource "aws_s3_bucket_logging" "session_logs_bucket" {
  bucket = aws_s3_bucket.session_logs_bucket.id

  target_bucket = aws_s3_bucket.session_logs_bucket.id
  target_prefix = "log/"
}
```

There were a couple of breaking changes made to the bastion module around adding randomness to resource names so we could have the ability to run automated tests.

Is this happening with a brand new environment? Or did you update the terraform code for an existing environment and try to apply?

**Comment by RothAndrew** [comment]
The prior state (where target_bucket is set to the access logs bucket) looks to be the incorrect one, that it's now trying to correct to the session logs bucket. Did we inadverdently fix a bug that caused this resource to point at the wrong bucket and that's why you're seeing a change?

**Comment by blancharda** [comment]
Notable thing I should have mentioned 🙈 

I'm pinned to `v0.0.0-alpha.5`

**Comment by RothAndrew** [comment]
I have a strong suspicion that this is already resolved. Let's close for now and reopen if that turns out to not be the case.

**Comment by blancharda** [comment]
Sorry for the rabbit hole 😆
