### ISSUE TITLE
Remove `manage_aws_auth_configmap` variable from complete example

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/iac#119]
AFAIK, in the complete example, `manage_aws_auth_configmap` should be true if `enable_eks_managed_nodegroups` is true, otherwise it should be false. We can simplify things by deleting the `manage_aws_auth_configmap` variable and using logic to set its value in the upstream module instead.

**Comment by ntwkninja** [comment]
@zack-is-cool @RothAndrew is this related to the consistent pipeline failures I've been experiencing the past few days?

```
TestExamplesCompleteSecure 2023-04-20T15:11:12Z logger.go:66: module.eks.module.aws_eks.kubernetes_config_map.aws_auth[0]: Still creating... [10m10s elapsed]
```
