### ISSUE TITLE
Misconfigured bucket logging in s3-irsa module

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/iac#125]
```
resource "aws_s3_bucket_logging" "logging" {
  bucket = module.s3_bucket.s3_bucket_id

  target_bucket = module.s3_bucket.s3_bucket_id
  target_prefix = "log/"
}
```

because `bucket` and `target_bucket` is the same bucket, this will create an infinite loop and cost a lot of money.

Ref: https://repost.aws/knowledge-center/s3-server-access-logs-same-bucket

**Comment by RothAndrew** [comment]
Looks like #117 added this. cc @brianrexrode

**Comment by brianrexrode** [comment]
I copied that resource directly from the https://github.com/defenseunicorns/terraform-k8s-tfstate-backend/blob/main/modules/backend/main.tf

I'll research and see what other options there are for this resource.

**Comment by RothAndrew** [comment]
We'll need to change it there too then. That code was copied over earlier. This got fixed in the bastion module in #107, looks like there's more places it was needed

**Comment by brianrexrode** [comment]
We are talking about/contemplating creating something like a general "access-logs" s3 bucket and just have all s3 bucket logging go there. 

Any thoughts @RothAndrew ?

**Comment by RothAndrew** [comment]
works for me, though we'd need to have it passed in as an input to avoid making the various modules tightly coupled

**Comment by RothAndrew** [comment]
Picking this up. Initial design is to

* Not create the logging bucket
* Have an optional input variable to pass in the ID of the logging bucket to use, and one for the path to put the logs in the bucket
* If a logging bucket ID is passed in using the variable, set up logging to that bucket. If it isn't, don't set up access logging.
