### ISSUE TITLE
Add linting pipeline for PRs

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#13]
Looking at 
- [tflint](https://github.com/terraform-linters/tflint) a linter for Terraform templates that helps enforce best practices and detect issues early in the development process
- [terraform fmt](https://developer.hashicorp.com/terraform/cli/commands/fmt) as pre-commit

**Comment by RothAndrew** [comment]
Terraform fmt is done. Let's close this issue as #41 talks purely about just enabling `tflint`

**Comment by RothAndrew** [comment]
Derp, just realized this issue is predominantly about doing this stuff in a pipeline. I'll open a new PR that talks about running all pre-commit hooks in a pipeline, that'll meet that outcome that is being looked for.
