### ISSUE TITLE
create_aws_auth_configmap should be a boolean input variable

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/iac#149]
Ran into a bug around the eks module's local for `create_aws_auth_configmap` logic. 
Simplest solution: make it a boolean var like the upstream.

Kind of a strange use case, but our module should be modular.

Error replication:
1. Deploy managed and self managed node groups
2. Try to destroy just the managed node groups by emptying the managed node group map. Scenario would be to destroy the managed node groups, deploy new ones, whatever.
  - This then essentially changes the logic around `create_aws_auth_configmap`, sets it to true, and tries to _create it_ in the upstream module. The issue here is, `aws-auth` configmap already exists due to previously deploying eks managed node groups on cluster instantiation 
3. receive error:
│ Error: configmaps “aws-auth” already exists
│ 
│   with module.eks.module.aws_eks.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/eks.aws_eks/main.tf line 536, in resource “kubernetes_config_map” “aws_auth”:
│  536: resource “kubernetes_config_map” “aws_auth” {

**Comment by RothAndrew** [comment]
Alternative proposition: we should stop supporting the simultaneous use of managed and self-managed nodes. 

We have no evidence or feedback that such a configuration has ever been or will ever be needed. Supporting it is adding unneeded complexity and work.
