### ISSUE TITLE
EKS Refactor - Review IAM policy for EKS

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#18]
~~https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-new-vpc#minimum-iam-policy~~

~~https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-new-vpc/min-iam-policy.json#L102~~

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v4.24.0/examples/eks-cluster-with-new-vpc#minimum-iam-policy

https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v4.24.0/examples/eks-cluster-with-new-vpc/min-iam-policy.json#L102

edit: Implement EKS Blueprints production IAM policy recommendations

**Comment by RothAndrew** [comment]
Links are dead. Need more detail before this is able to be picked up and worked.

**Comment by ntwkninja** [comment]
updated links

**Comment by ntwkninja** [comment]
No longer applicable
