### ISSUE TITLE
Update Node groups with BB optimized values

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#19]
Configure EKS nodegroups in complete-example min.tf with minimum requirements to run a medium BB deployment 

- [x] Expose eks-nodegroup settings in the complete-example main.tf / add necessary vars for these [lines](https://github.com/defenseunicorns/iac-archive/blob/main/modules/eks/main.tf#L78-L145)
- [ ] Determine if SSO needs dedicated nodes
- [ ] Adjust node group settings for BB Core + KC + podinfo needs

**Comment by JaseKoonce** [comment]
Reviewed AWS pricing, it appears going with x3 m5xlarge and allow autoscaling would be the most cost effective option. 

details:
m5.xlarge | 4 vCPUs | 16 GiB | Up to 10 Gigabit Networking | EBS only | 0.242 per hour |

**Comment by RothAndrew** [comment]
Context on other stuff that is going on that will affect this issue:

* We're working on simplifying the examples such that `complete-managed-nodegroup` and `complete-self-managed-nodegroup` are merged into one example called `complete` that is able to be run in either "insecure mode" or "secure mode" by using a different overlay tfvars file
* Instance type is defined in the node group object(s). The modules just take the whole object as a variable. The example currently hard codes the whole node group object(s). I definitely feel like there is room for improvement on how we do that.

**Comment by ntwkninja** [comment]
Re: the whole object for nodegroup variable, each environment is going to be drastically different when it comes to resources. How many pods per cluster, number of nodes, resources needed, tainted nodes for sensitive workloads, etc.

All that to say it may be difficult to make it useful and highly opinionated

**Comment by ntwkninja** [comment]
moving SSO piece to separate issue and closing pending additional feedback
