### ISSUE TITLE
Build Zarf package to execute terraform

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#22]
- [X] Deploy iac with zarf / export package variables
  - https://github.com/defenseunicorns/iac/blob/main/examples/zarf-complete-example/zarf.yaml
  - Deploy base IaC (VPC, bastion, Loki S3 bucket and EKS) via Zarf
- [ ] Instantiate / bootstrap EKS cluster with BB Core + KC + podinfo using zarf
  - https://github.com/defenseunicorns/zarf-package-big-bang/blob/development/zarf.yaml
  - Deploy BB Core + KeyCloak + authsvc + podinfo  
  - Deploy RDS database / figure out how to use Zarf to write db secret to be consumed by KC

**Comment by ntwkninja** [comment]
related issues: 
https://github.com/defenseunicorns/iac/issues/9
https://github.com/defenseunicorns/zarf/issues/1141

**Comment by RothAndrew** [comment]
For the 2nd checkbox, we are doing some of the stuff like the RDS database, and for other stuff it's likely gonna happen over in https://github.com/defenseunicorns/zarf-package-big-bang. Should we just close this issue and open a couple of new ones that more closely target what still needs to be done?

**Comment by ntwkninja** [comment]
Closing in favor of more granular issues
