### ISSUE TITLE
Variabilize EKS Configs

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#32]
EKS configs need to be exposed in order for the module to be extensible

- [x] Varibilize self-managed node group settings: https://github.com/defenseunicorns/iac/blob/main/modules/eks/main.tf#L97-L164
- [x] Varibilize EKS Add-Ons: https://github.com/defenseunicorns/iac/blob/main/modules/eks/eks-addons.tf#L15-L44
### moved the item below to its own issue
- [ ] ~~Allow use of managed node groups (currently not built for these). Toggling between managed / self-managed node groups will require conditionals in a few places.~~

**Comment by JaseKoonce** [comment]
EKS configurations have been variabilized and the branch has successfully been merged into main.
