### ISSUE TITLE
Parent Epic: AWS + EKS + Big Bang Core + Keycloak IaC

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#33]
As a unicorn engineer responsible for AWS infrastructure, I need the ability to deploy the infrastructure in a repeatable/consumable way that is secure, compliant and authorized.

AC:
- I have the ability to consume IaC modules to deploy AWS resources that includes a secure kubernetes cluster ready to accept zarf package deployments of Bigbang ~~and mission apps~~.
- The modules have a robust automated CI pipeline
- The modules live in GitHub as public repos

Scope:
VPCs, subnets, NAT gwys, TGWs
EKS, self-managed workers
Loki Buckets / Dynamodb table
Keycloak Database
~~Rt 53 entries~~
~~EC2 Gitlab Runner~~
Bastion

Notes:
- Solution is intended to be repeatable, reusable, and consumable IaC modules that can be used in other environments instead of a one off solution.

Edit: removed mission apps, Rt 53 entries & EC2 GL runner from AC as these are more implementation-specific items and not core UDS things

**Comment by RothAndrew** [comment]
Is the above description still accurate? Let's update it to reflect any changes in technical and/or organizational areas since it was written in january

**Comment by ntwkninja** [comment]
updated original comment to reduce scope

**Comment by ntwkninja** [comment]
closing since issues are captured / being tracked
