### ISSUE TITLE
Add vSphere IaC modules

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/iac#43]
Details TBD

**Comment by RothAndrew** [comment]
🤮

**Comment by RothAndrew** [comment]
Needs more details before one is able to pick this up and work it.

**Comment by RothAndrew** [comment]
Closing this due to lack of details. Feel free to open a new issue that meets our [Definition of Ready](https://github.com/defenseunicorns/iac/blob/main/CONTRIBUTING.md#definition-of-ready-for-a-backlog-item)
