### ISSUE TITLE
Create Production Ready DynamoDB Module

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/iac#6]
This may be done, just making issues for each of the components we need for https://github.com/defenseunicorns/stack/issues/1 

Need for loki logging

**Comment by ntwkninja** [comment]
does loki need S3, DynamoDB or both?

https://repo1.dso.mil/platform-one/big-bang/customers/bigbang/-/blob/master/terraform/modules/loki-objectstore/main.tf

https://grafana.com/docs/loki/latest/operations/storage/

**Comment by ntwkninja** [comment]
we currently have it built to use this [S3 module]([s3-irsa](https://github.com/defenseunicorns/iac/tree/main/modules/s3-irsa))

**Comment by runyontr** [comment]
It needs both.  it needs the dynamoDB for keeping track of the indices for the logs.  The logs themselves are then stored in the S3 buckets from #5
