### ISSUE TITLE
Investigate Delta required to support Hypervisor with EKS IaC

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/iac#72]
Context: Kubevirt needs virtualization enabled on Kubernetes nodes, AWS does not support virtualization on normal EC2 instances. Possibly only supported on Bare metal.

**Comment by RothAndrew** [comment]
Primary/first customer doesn't need virtualization. Suggest we create a label called "icebox" or otherwise close this for now and reopen it after we start expanding to more use cases. cc @ntwkninja

**Comment by andrewg-xyz** [comment]
Initial prototype work can be reviewed in the [baffles-infra](https://github.com/defenseunicorns/baffles-infra/tree/aws-eks-terraform) 

point on contact: @TristanHoladay

**Comment by RothAndrew** [comment]
Closing this as out of scope of this repo
