### ISSUE TITLE
Change EKS module to conform to EKS Blueprints direction

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/iac#73]
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/docs/v5-direction/DIRECTION_v5.md#notable-changes

**Comment by RothAndrew** [comment]
More info needed. @zack-is-cool are you working on stuff for this already? I remember you had mentioned it. Need better context on what is needed and what is already being worked.

**Comment by RothAndrew** [comment]
@zack-is-cool would you mind pushing up a draft PR?

Will this work that you are doing also cover #75?

**Comment by ntwkninja** [comment]
spot on @zack-is-cool 

VPC CNI with custom networking + calico CNI could not be deployed with EKS blueprints because it was missing the `before_compute` flag and EKS blueprints has pivoted so we couldn't work an upstream PR

@RothAndrew Zack is working #73 & #75

**Comment by RothAndrew** [comment]
Sounds good. Recommend we get the automated testing stuff in place before a big change like this gets merged.
